language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq

install:
  - |
    sudo apt-get -y install gpm apt-file git wget unzip gcc make autoconf automake libtool \
    g++ autoconf-archive pkg-config libglib2.0-dev libglibmm-2.4-dev libzip-dev \
    libusb-1.0-0-dev libftdi-dev libvisa-dev libieee1284-3-dev check doxygen \
    python-numpy python-dev python-gi-dev python-setuptools swig sdcc python3-dev \
    libboost1.55-all-dev mesa-common-dev libgl1-mesa-dev qt510base qt510-meta-full
  - source /opt/qt510/bin/qt510-env.sh
  - sudo rm -rf /usr/bin/cmake /usr/local/cmake-* /usr/local/bin/cmake || true # Needed on Travis CI; don't do this on other systems!
  - wget "https://github.com/Kitware/CMake/releases/download/v3.13.2/cmake-3.13.2-Linux-x86_64.tar.gz" ; sudo tar xf  cmake*.tar.gz --strip-components=1 -C /usr

script:
  # Build qwt
  - wget "https://sourceforge.net/projects/qwt/files/qwt/6.1.4/qwt-6.1.4.tar.bz2/download" --trust-server-names
  - tar xf qwt-*.tar.bz2
  - cd qwt-*/
  - qmake qwt.pro
  - make -j$(nproc)
  - sudo make install
  - cd ..
  # Build smuview
  - git clone https://github.com/knarfS/sigrok-util.git
  - cd sigrok-util
  - git checkout smuview
  - cd cross-compile/linux
  - ./sigrok-cross-linux-smuview
  - make INSTALL_ROOT=appdir -j$(nproc) install
  - find .
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh APPNAME*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
